class Arguments:
    subscriber_count: int
    execution_duration_in_days: float
    rebound_trigger_percentage: float
    interest_rate_percentage: float
    interest_period_in_days: float
    buy_sell_ratio: float
    token_y_count: int
    token_x_count: int
    min_transaction_amount: int
    max_transaction_amount: int
    min_transaction_time: int
    max_transaction_time: int